# Generated by Django 3.2.4 on 2021-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': "Quiz's"},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='isActive',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.BooleanField(default=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz',
            field=models.TextField(verbose_name='Quiz'),
        ),
    ]
